# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: PropertyLookup.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'PropertyLookup.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14PropertyLookup.proto\"+\n\rLookupRequest\x12\x0b\n\x03zip\x18\x01 \x01(\x05\x12\r\n\x05limit\x18\x02 \x01(\x05\"#\n\x0eLookupResponse\x12\x11\n\taddresses\x18\x01 \x03(\t2@\n\x0ePropertyLookup\x12.\n\x0bLookupByZip\x12\x0e.LookupRequest\x1a\x0f.LookupResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PropertyLookup_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOOKUPREQUEST']._serialized_start=24
  _globals['_LOOKUPREQUEST']._serialized_end=67
  _globals['_LOOKUPRESPONSE']._serialized_start=69
  _globals['_LOOKUPRESPONSE']._serialized_end=104
  _globals['_PROPERTYLOOKUP']._serialized_start=106
  _globals['_PROPERTYLOOKUP']._serialized_end=170
# @@protoc_insertion_point(module_scope)
